In [3]:
import pandas as pd
import numpy as np
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException 
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import re
import time

In [4]:
def set_up_driver():
    chrome_options = Options()
    chrome_options.add_argument("--headless") 
    chrome_options.add_argument("--disable-gpu")
    chrome_options.add_argument("start-maximized")
    chrome_options.add_argument("--disable-blink-features=AutomationControlled") # Tắt tính năng phát hiện tự động của trình duyệt
    chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"]) # Loại bỏ thông báo "Chrome is being controlled by automated test software"
    chrome_options.add_experimental_option('useAutomationExtension', False) # Vô hiệu hóa tiện ích mở rộng tự động hóa
    driver = webdriver.Chrome(options=chrome_options)
    return driver

In [480]:
def get_text(driver, selector):
    try:
        el = driver.find_element(By.CSS_SELECTOR, selector)
        return el.text.strip()
    except:
        return None

In [5]:
def get_section_detail(driver, title):
    try:
        
        # Tìm container chứa nội dung
        container = driver.find_element(By.CSS_SELECTOR, "div.render-html.text-14")
        
        # Lấy tất cả h3 trong container
        h3s = container.find_elements(By.TAG_NAME, "h3")
        title_norm = title.lower().strip()
        
        for h3 in h3s:
            h3_text = h3.get_attribute("textContent") or ""
            
            if title_norm in h3_text.lower():
                # Lấy siblings trực tiếp từ h3
                siblings = h3.find_elements(By.XPATH, "./following-sibling::*")
                
                content = []
                for sib in siblings:
                    tag = sib.tag_name.lower()
                    
                    # Dừng khi gặp h3 tiếp theo
                    if tag == "h3":
                        break
                    
                    # Lấy text
                    t = sib.get_attribute("textContent") or ""
                    t = t.strip()
                    if t:
                        content.append(t)
                
                return "\n".join(content) if content else None
                
    except:
        pass
    return None

In [6]:
def get_product_images(driver):
    images = []

    try:
        img_elements = driver.find_elements(By.CSS_SELECTOR, "img[src*='Products/Images'], img[src*='cdn.tgdd.vn']")

        for img in img_elements:
            src = img.get_attribute("src")
            if src and "Products/Images"in src:
                if "https://cdn.tgdd.vn" in src:
                    match = re.search(r'(https://cdn\.tgdd\.vn/Products/Images/[^\s]+)', src)
                    if match:
                        original_url = match.group(1)
                        if original_url not in images:
                            images.append(original_url)
                elif src not in images:
                    images.append(src)
    except Exception as e:
        print(f"Error {e}")
        pass
    return images

In [7]:
# Lấy thông tin từ bảng grid
def get_product_infomation(driver, label):
    try:
        rows = driver.find_elements(By.CSS_SELECTOR, "#contentRef .grid.grid-cols-3")
        for row in rows:
            label_el = row.find_element(By.CSS_SELECTOR, "div.text-13.font-bold")
            label_text = label_el.get_attribute("textContent") or ""
            
            if label.lower() in label_text.lower():
                value_el = row.find_element(By.CSS_SELECTOR, "div.col-span-2 div.mr-2")
                value_text = value_el.get_attribute("textContent") or ""
                return value_text.strip()
    except Exception as e:
        print(f"Get product information error: {e}")
        pass
    return None

In [8]:
def get_medicine_data(driver):
    try:
        WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, "div[class*='text-20'][class*='font-bold']")))
    except:
        pass

    name = get_text(driver, "div.text-20.font-bold")
    if not name:
        try:
            name = driver.title.split(' - ')[0].strip()
        except:
            name = None

    price = None
    try:
        price_el = driver.find_element(By.CSS_SELECTOR, "body > div.bg-secondary-300 > div.w-1200px.mx-auto.min-h-screen.relative.z-1 > div > div.ml-4.flex.h-auto.w-\[540px\].cursor-default.flex-col.gap-20px > div:nth-child(1) > div:nth-child(4) > div > p")
        price = price_el.text.strip()
    except:
        pass
    

    images = get_product_images(driver)


    expand_button_1 = driver.find_element(By.XPATH, "//*[@id='contentRef']/div/div[6]/button")
    expand_button_1.click()
    time.sleep(2)

    cong_dung_tom_tat = get_product_infomation(driver, "Công dụng")
    thanh_phan_chinh = get_product_infomation(driver, "Thành phần chính")
    doi_tuong = get_product_infomation(driver, "Đối tượng sử dụng")
    thuong_hieu = get_product_infomation(driver, "Thương hiệu")
    noi_san_xuat = get_product_infomation(driver, "Nơi sản xuất")
    dang_bao_che = get_product_infomation(driver, "Dạng bào chế")
    han_dung = get_product_infomation(driver, "Hạn dùng")


    close_btn = driver.find_element(By.CSS_SELECTOR, "button[class*='absolute'][class*='right']")
    close_btn.click()
    time.sleep(2)



    expand_button_2 = driver.find_element(By.XPATH, "//*[@id='contentRef']/div/div[4]/button")
    expand_button_2.click()
    time.sleep(2)

    thanh_phan_chi_tiet = get_section_detail(driver, "1. Thành phần")
    cong_dung_chi_tiet = get_section_detail(driver, "2. Công dụng")
    cach_dung = get_section_detail(driver, "3. Cách dùng")
    chong_chi_dinh = get_section_detail(driver, "4. Chống chỉ định")
    tac_dung_phu = get_section_detail(driver, "5. Tác dụng phụ")
    luu_y = get_section_detail(driver, "6. Lưu ý")

    return {
        "ten_thuoc": name,
        "gia": price,
        "hinh_anh": "|".join(images) if images else None,
        "cong_dung_tom_tat": cong_dung_tom_tat,
        "thanh_phan_chinh": thanh_phan_chinh,
        "doi_tuong": doi_tuong,
        "thuong_hieu": thuong_hieu,
        "noi_san_xuat": noi_san_xuat,
        "dang_bao_che": dang_bao_che,
        "han_dung": han_dung,
        "thanh_phan_chi_tiet": thanh_phan_chi_tiet,
        "cong_dung_chi_tiet": cong_dung_chi_tiet,
        "cach_dung": cach_dung,
        "chong_chi_dinh": chong_chi_dinh,
        "tac_dung_phu": tac_dung_phu,
        "luu_y": luu_y
    }

<>:16: SyntaxWarning: invalid escape sequence '\['
<>:16: SyntaxWarning: invalid escape sequence '\['
C:\Users\Admin\AppData\Local\Temp\ipykernel_3200\1769263606.py:16: SyntaxWarning: invalid escape sequence '\['
  price_el = driver.find_element(By.CSS_SELECTOR, "body > div.bg-secondary-300 > div.w-1200px.mx-auto.min-h-screen.relative.z-1 > div > div.ml-4.flex.h-auto.w-\[540px\].cursor-default.flex-col.gap-20px > div:nth-child(1) > div:nth-child(4) > div > p")

In [9]:
def crawl_ankhang_medicines(csv_path, out_csv):
    df = pd.read_csv(csv_path)
    driver = set_up_driver()
    results = []

    try:

        for i, row in df.iterrows():
            url = row['link']
            category = row.get('category', '')
            drug_type = row.get('drug_type', '')

            try:
                driver.get(url)
                data = get_medicine_data(driver)
                data['url'] = url
                data['category'] = category
                data['drug_type'] = drug_type
                results.append(data)
                print(f"[{i+1}/{len(df)}] crawled: {data['ten_thuoc']}")
            except Exception as e:
                results.append({'url': url, 'error': str(e)})
                print(f"[{i+1}/{len(df)}] failed: {url} with error {e}")

            time.sleep(2)  

            if (i + 1) % 50 == 0:
                pd.DataFrame(results).to_csv(out_csv, index=False, encoding='utf-8-sig')
                print(f"Saved {len(results)} records to {out_csv}")

        
    finally:
        driver.quit()
        pd.DataFrame(results).to_csv(out_csv, index=False, encoding='utf-8-sig')
        print(f"Đã lưu {len(results)} sản phẩm vào {out_csv}")

In [486]:
driver = set_up_driver()
driver.get("https://www.nhathuocankhang.com/thuoc-bo-va-vitamin/thuoc-bo-sung-vitamin-b-timi-roitin-120-vien?sku=1193668000314")
time.sleep(3)
data = get_medicine_data(driver)
print(data)
driver.quit()

{'ten_thuoc': 'Timi Roitin trị viêm dây thần kinh, thoái hóa khớp (24 vỉ x 5 viên)', 'gia': '528.000₫', 'hinh_anh': 'https://cdn.tgdd.vn/Products/Images/10053/130480/timi-roitin-2-1.jpg|https://cdn.tgdd.vn/Products/Images/10053/130480/timi-roitin-3-1.jpg|https://cdn.tgdd.vn/Products/Images/10053/130480/timi-roitin-0-1.jpg', 'cong_dung_tom_tat': 'Bổ sung vitamin nhóm B, điều trị viêm dây thần kinh ngoại biên, viêm đa dây thần kinh,...', 'thanh_phan_chinh': 'Chondroitin, Vitamin B5, Fursultiamine, Vitamin PP, Vitamin B6, Vitamin B2', 'doi_tuong': 'Người lớn', 'thuong_hieu': 'Phil Inter Pharma', 'noi_san_xuat': 'Việt Nam', 'dang_bao_che': 'Viên nang mềm', 'han_dung': '36 tháng kể từ ngày sản xuất', 'thanh_phan_chi_tiet': 'Hoạt chất: Chondroitin sulfate natri 90mg, Nicotinamide 50mg, Fursultiamine 50mg, Riboflavin 6mg, Pyridoxine HCl 25mg, Calci pantothenate 15mg.\nTá dược: Dầu đậu nành, Sáp ong trắng, Dầu Lecithin, Dầu cọ, Gelatin, Glycerin đậm đặc, D-sorbitol 70%, Ethyl vanillin, Màu vàng số 4, Oxyd sắt đỏ, Màu xanh số 1, Màu đỏ số 40, Titan dioxide, Nước tinh khiết.', 'cong_dung_chi_tiet': '- Bổ sung các vitamin nhóm B trong các trường hợp nghiện rượu, ốm nặng, biếng ăn, cơ thể suy nhược, mỏi cơ, viêm miệng, viêm lưỡi, bệnh đường ruột (như tiêu chảy, viêm ruột).\n- Điều trị viêm dây thần kinh ngoại biên, viêm đa dây thần kinh, tê chân tay, đau lưng, đau do thoái hóa khớp (viêm khớp), khô mắt, đau nhức mắt.', 'cach_dung': 'Người lớn: Uống 1 viên/ngày.\n- Quá liều\nDùng thuốc quá liều có thể gây đau bụng, tiêu chảy, mệt mỏi,...', 'chong_chi_dinh': '- Quá mẫn với bất cứ thành phần nào của thuốc.\n- Bệnh gan nặng.\n- Loét dạ dày tiến triển.\n- Xuất huyết động mạch.\n- Hạ huyết áp nặng.', 'tac_dung_phu': 'TIMIROITIN thường được dung nạp tốt khi dùng ở liều điều trị, đôi khi thấy rối loạn nhẹ đường tiêu hoá biểu hiện như buồn nôn, nôn, tiêu chảy,...\nNicotinamid\nLiều nhỏ nicotinamid thường không độc, tuy nhiên nếu dùng liều cao, như trong trường hợp điều trị pellagra, có thể xảy ra một số tác dụng phụ sau đây, những tác dụng phụ này sẽ hết sau khi ngừng thuốc.\nThường gặp, ADR > 1/100.\nTiêu hóa: Buồn nôn.\nKhác: Đỏ bừng mặt và cổ, ngứa, cảm giác rát bỏng, buốt hoặc đau nhói ở da.\nÍt gặp, 1/1000 < ADR < 1/100.\nTiêu hóa: Loét dạ dày tiến triển, nôn, chán ăn, đau khi đói, đầy hơi, tiêu chảy.\nDa: Khô da, tăng sắc tố, vàng da.\nChuyển hóa: Suy gan, giảm dung nạp glucose, tăng tiết tuyến bã nhờn, làm bệnh gút nặng thêm.\nKhác: Tăng glucose huyết, tăng uric huyết, cơn phế vị - huyết quản, đau đầu và nhìn mờ, hạ huyết áp, chóng mặt, tim đập nhanh, ngất.\nHiếm gặp, ADR < 1/1000.\nLo lắng, hốt hoảng, glucose niệu, chức năng gan bất bình thường [bao gồm tăng bilirubin huyết thanh, tăng AST (SGOT), ALT (SGPT) và LDH], thời gian prothrombin bất bình thường, hạ albumin huyết, choáng phản vệ.\nPyridoxin\nDùng liều 200mg/ngày và dài ngày (trên 2 tháng) có thể gây bệnh thần kinh ngoại vi nặng, tiến triển từ dáng đi không vững và tê cóng bàn chân đến tê cóng và vụng về bàn tay. Tình trạng này có thể hồi phục khi ngừng thuốc, mặc dù vẫn còn để lại ít nhiều di chứng.', 'luu_y': '- Thận trọng khi sử dụng\n- Khi sử dụng nicotinamid liều cao cho những trường hợp sau: Tiền sử loét dạ dày, bệnh túi mật, tiền sử có vàng da hoặc bệnh gan, bệnh gút, viêm khớp do gút, và bệnh đái tháo đường.\n- Sau thời gian dài dùng pyridoxin với liều 200mg/ngày, có thể đã thấy biểu hiện độc tính thần kinh (như bệnh thần kinh ngoại vi nặng và bệnh thần kinh cảm giác nặng). Dùng liều 200mg mỗi ngày, kéo dài trên 30 ngày có thể gây hội chứng lệ thuộc pyridoxin.\n- Cần thận trọng khi dùng cho phụ nữ có thai và cho con bú vì thuốc đi qua nhau thai và sữa mẹ, có thể xảy ra hiện tượng thừa vitamin nhóm B ở trẻ em.\n- Thuốc làm cho nước tiểu có màu vàng, có thể ảnh hưởng đến kết quả xét nghiệm lâm sàng.\n- Thai kỳ và cho con bú\nThuốc đi qua sữa mẹ và nhau thai, do vậy chỉ cần dùng thuốc khi thấy thiếu hụt các thành phần của thuốc trong khẩu phần ăn hàng ngày.\n- Tương tác thuốc\n- Vitamin B6 làm giảm tác dụng của thuốc kháng lao isoniazid và levodopa.\n- Nicotinamide làm tăng tác dụng của thuốc hạ áp loại chẹn alpha-adrenergic và của carbamazepin nếu dùng chung.'}

In [487]:
crawl_ankhang_medicines("ankhang_medicine_links.csv", "ankhang_medicines_data_demo.csv")

[1/2127] crawled: Timi Roitin trị viêm dây thần kinh, thoái hóa khớp (24 vỉ x 5 viên)
[2/2127] crawled: B Complex C bổ sung vitamin nhóm B và vitamin C (10 vỉ x 10 viên)
[3/2127] failed: https://www.nhathuocankhang.com/thuoc-bo-va-vitamin/cezinco-110mg-5ml-h-30-ong?sku=1193668000849 with error Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='contentRef']/div/div[4]/button"}
  (Session info: chrome=145.0.7632.45); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ff721e94325
	0x7ff721e94380
	0x7ff721c2d49d
	0x7ff721c882fe
	0x7ff721c8860c
	0x7ff721cd8b67
	0x7ff721cd5728
	0x7ff721c78e38
	0x7ff721c79d23
	0x7ff722163090
	0x7ff72215d918
	0x7ff72217dc8a
	0x7ff721eb06d5
	0x7ff721eb967c
	0x7ff721e9d684
	0x7ff721e9d836
	0x7ff721e83347
	0x7ffd717ae8d7
	0x7ffd722cc40c

[4/2127] crawled: Vitamin PP 50 Pharmedic ngăn ngừa thiếu nicotinamide lọ 60 viên
[5/2127] crawled: Agi-Calci bổ sung canxi, trị loãng xương (20 vỉ x 10 viên)
[6/2127] crawled: Vitamin B1 Mekophar 250mg trị các bệnh thiếu vitamin B1 (10 vỉ x 10 viên)
[7/2127] crawled: Dung dịch uống Calciumboston Ascorbic trị thiếu canxi, vitamin C (20 ống x 10ml)
[8/2127] crawled: Viên Hà Thủ Ô Extracap trị suy nhược, tóc bạc sớm (5 vỉ x 10 viên)
[9/2127] crawled: Hỗn dịch uống Zedcal bổ sung canxi, magie, kẽm và vitamin D3 chai 200ml
[10/2127] crawled: Franvit C.Ex 500 bổ sung vitamin C, tăng đề kháng (5 vỉ x 10 viên)
[11/2127] crawled: Magne B6 Corbière trị thiếu Magnesi và vitamin B6 (5 vỉ x 10 viên)
[12/2127] crawled: Bofit F trị thiếu máu do thiếu sắt, acid folic (3 vỉ x 10 viên)
[13/2127] crawled: Biotin 5mg Mediplantex hỗ trợ trị viêm da, rụng tóc (2 vỉ x 10 viên)
[14/2127] failed: https://www.nhathuocankhang.com/thuoc-bo-va-vitamin/mangistad?sku=1193668000755 with error Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='contentRef']/div/div[4]/button"}
  (Session info: chrome=145.0.7632.45); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ff721e94325
	0x7ff721e94380
	0x7ff721c2d49d
	0x7ff721c882fe
	0x7ff721c8860c
	0x7ff721cd8b67
	0x7ff721cd5728
	0x7ff721c78e38
	0x7ff721c79d23
	0x7ff722163090
	0x7ff72215d918
	0x7ff72217dc8a
	0x7ff721eb06d5
	0x7ff721eb967c
	0x7ff721e9d684
	0x7ff721e9d836
	0x7ff721e83347
	0x7ffd717ae8d7
	0x7ffd722cc40c

[15/2127] crawled: Vitamin C MKP 500mg trị thiếu vitamin C (20 vỉ x 10 viên)
[16/2127] crawled: Dung dịch uống A.T Calci Plus cung cấp canxi cho cơ thể (30 ống x 10ml)
[17/2127] crawled: Enervon bổ sung vitamin nhóm B và vitamin C (10 vỉ x 10 viên)
[18/2127] crawled: Dung dịch uống Pokemine 50mg hỗ trợ bổ sung sắt (20 ống x 10ml)
[19/2127] crawled: Viên nén sủi bọt Calcium Boston 500mg trị loãng xương, nhuyễn xương tuýp 20 viên
[20/2127] crawled: Viên nén sủi bọt CalSource Sandoz 600 + Vitamin D3 trị loãng xương tuýp 10 viên
[21/2127] crawled: Magnesium - B6 TV.Pharm làm giảm các triệu chứng thiếu hụt magnesi (10 vỉ x 10 viên)
[22/2127] crawled: Dasbrain bổ não, tăng cường miễn dịch lọ 30 viên
[23/2127] crawled: Hà thủ ô Domesco bổ thận, bổ huyết (3 vỉ x 10 viên)
[24/2127] crawled: Scanneuron - Forte hỗ trợ trị các rối loạn hệ thần kinh (10 vỉ x 10 viên)
[25/2127] crawled: Dung dịch uống Gadacal bổ sung calci, lysin và các vitamin cho cơ thể (20 ống x 10ml)
[26/2127] crawled: Bisbeta 120 kiểm soát cân nặng, hỗ trợ trị béo phì (2 vỉ x 21 viên)
[27/2127] crawled: Caldihasan trị loãng xương, còi xương (3 vỉ x 10 viên)
[28/2127] crawled: Hỗn dịch uống Calcigenol Vitamine bổ sung canxi, phòng loãng xương chai 360g
[29/2127] crawled: Dung dịch uống A.TAscorbic Syrup 100mg/5ml bổ sung vitamin C (30 ống x 10ml)
[30/2127] crawled: Vitamin A-D trị các triệu chứng do thiếu vitamin A, D (5 vỉ x 10 viên)
[31/2127] crawled: Ferrovit bổ sung sắt và axit folic, trị thiếu máu (5 vỉ x 10 viên)
[32/2127] crawled: Dung dịch uống Hemafolic ngăn ngừa và trị thiếu máu do thiếu sắt (10 ống x 10ml)
[33/2127] crawled: Siscozol Tab Ca++ bổ sung canxi, trị loãng xương (10 vỉ x 10 viên)
[34/2127] crawled: PM Procare bổ sung vitamin, khoáng chất cho phụ nữ mang thai lọ 30 viên
[35/2127] crawled: Siro Saferon 50mg/5ml trị thiếu máu, thiếu sắt chai 100ml
[36/2127] crawled: Tardyferon B9 dự phòng thiếu sắt và acid folic (3 vỉ x 10 viên)
[37/2127] crawled: Logpatat trị các bệnh về mắt, suy giảm thị lực (6 vỉ x 10 viên)
[38/2127] crawled: Briozcal bổ sung canxi và vitamin D3, điều trị loãng xương (3 vỉ x 10 viên)
[39/2127] crawled: Vitamin A 5000IU phòng và trị các triệu chứng thiếu vitamin A (10 vỉ x 10 viên)
[40/2127] crawled: Tozinax 70mg phòng và điều trị thiếu kẽm (10 vỉ x 10 viên)
[41/2127] crawled: Homtamin Ginseng bổ sung vitamin và khoáng chất, giảm mệt mỏi (12 vỉ x 5 viên)
[42/2127] crawled: Magnesi B6 Phong Phú trị thiếu magie, giảm lo âu, căng thẳng (5 vỉ x 10 viên)
[43/2127] crawled: Cốm Bổ Zinc - Kid Inmed 70mg bổ sung kẽm, trị tiêu chảy (25 gói x 3g)
[44/2127] crawled: Bequantene 100mg trị rụng tóc lan tỏa (2 vỉ x 10 viên)
[45/2127] crawled: Osteomed bổ sung canxi, magie, kẽm và vitamin D3 (2 vỉ x 15 viên)
[46/2127] crawled: Cao lỏng Traluvi giúp trẻ ăn ngon, ngừa mồ hôi trộm chai 100ml
[47/2127] crawled: PM NextG Cal bổ sung canxi, trị loãng xương (5 vỉ x 12 viên)
[48/2127] crawled: NateCal D3 bổ sung canxi và vitamin D, trị loãng xương lọ 60 viên
[49/2127] crawled: Enpovid E400 bổ sung vitamin E, ngừa lão hóa (10 vỉ x 10 viên)
[50/2127] crawled: Sirô Ceelin+Z phòng ngừa và điều trị thiếu vitamin C và thiếu kẽm chai 60ml
Saved 50 records to ankhang_medicines_data_demo.csv
[51/2127] crawled: Dung dịch uống Mumcal 500mg/10ml bổ sung và ngừa giảm canxi (20 ống x 10ml)
[52/2127] crawled: Dung dịch uống Hemopoly ngăn ngừa và trị thiếu máu do thiếu sắt (20 ống x 5ml)
[53/2127] crawled: Trineuron trị bệnh do thiếu vitamin nhóm B (5 vỉ x 10 viên)
[54/2127] crawled: Enat 400 bổ sung vitamin E, ngừa lão hóa (3 vỉ x 10 viên)
[55/2127] crawled: Viên nhai Saferon phòng và trị thiếu máu, thiếu sắt (3 vỉ x 10 viên)
[56/2127] crawled: PM Procare Diamond bổ sung vitamin, khoáng chất cho phụ nữ mang thai lọ 30 viên
[57/2127] crawled: Dung dịch uống Calcium Corbière Extra điều trị loãng xương, còi xương (30 ống x 10ml)
[58/2127] crawled: Viên sủi UPSA-C 1g trị thiếu hụt Vitamin C, cảm cúm, mệt mỏi tạm thời tuýp 10 viên
[59/2127] crawled: Admed trị tình trạng thiếu vitamin A-D (10 vỉ x 10 viên)
[60/2127] crawled: Viên nén sủi bọt Calcium Stella 500mg bổ sung calci, trị loãng xương tuýp 20 viên
[61/2127] crawled: Agifivit phòng và điều trị bệnh thiếu máu do thiếu sắt và acid folic (10 vỉ x 10 viên)
[62/2127] crawled: Viên nén sủi bọt Berocca Performance trị thiếu hụt vitamin B, C tuýp 10 viên
[63/2127] crawled: Agi-Neurin điều trị và dự phòng thiếu vitamin B1, B6, B12 (10 vỉ x 10 viên)
[64/2127] crawled: Magnesi - B6 Imexpharm trị thiếu magnesi riêng biệt hay kết hợp (10 vỉ x 10 viên)
[65/2127] crawled: Agirenyl 5000IU phòng và trị triệu chứng thiếu vitamin A (10 vỉ x 10 viên)
[66/2127] crawled: Cystine B6 Bailleul trị bệnh lý liên quan đến tóc, móng (1 vỉ x 20 viên)
[67/2127] crawled: Siro Snapcef 16 mg/10ml trị tiêu chảy, bổ sung kẽm hộp (20 ống x 10ml)
[68/2127] crawled: Viên sủi bọt Davita bone Sugar Free phòng và điều trị bệnh loãng xương tuýp 10 viên
[69/2127] crawled: Tobicom trị mỏi mắt, đau nhức mắt, suy giảm thị lực (18 vỉ x 10 viên)
[70/2127] crawled: Viên nhai Pm KiddieCal bổ sung canxi và vitamin D chai 30 viên
[71/2127] crawled: Vita C Glucose bổ sung vitamin C, tăng đề kháng (46 túi x 24 viên)
[72/2127] crawled: Dung dịch uống Calcium Corbière Extra bổ sung canxi, trị loãng xương (30 ống x 5ml)
[73/2127] crawled: Hà Thủ Ô Traphaco hỗ trợ trị thiếu máu, tóc bạc sớm (5 vỉ x 20 viên)
[74/2127] crawled: Vitamin B2 Traphaco 2mg dự phòng và điều trị thiếu vitamin B2 (6 vỉ x 30 viên)
[75/2127] crawled: Drimy bổ sung vitamin và khoáng chất (10 vỉ x 10 viên)
[76/2127] crawled: Orlistat Stada 120mg kiểm soát cân nặng, hỗ trợ trị béo phì (2 vỉ x 21 viên)
[77/2127] crawled: Cốm pha hỗn dịch uống Unikids Zinc 70 điều trị tiêu chảy cấp và mạn tính (24 gói x 1.5g)
[78/2127] crawled: Dung dịch uống Nadyfer trị thiếu máu do thiếu sắt (20 ống x 10ml)
[79/2127] crawled: Bột pha hỗn dịch uống Meza - Calci 1,65g điều trị hỗ trợ loãng xương (30 gói x 2g)
[80/2127] crawled: Obimin Multivitamins bổ sung vitamin, khoáng chất cho phụ nữ mang thai (10 vỉ x 10 viên)
[81/2127] crawled: Sáng mắt Traphaco trị các bệnh về mắt, suy giảm thị lực (10 vỉ x 10 viên)
[82/2127] crawled: Becoron-C tăng cường, củng cố hệ thống miễn dịch (10 vỉ x 10 viên)
[83/2127] crawled: Dung dịch tiêm Avastin 100mg/4ml điều trị ung thư đại, trực tràng chai 4ml
[84/2127] failed: https://www.nhathuocankhang.com/thuoc-tri-ung-thu/zoladex-inj-10-8mg?sku=1193692000032 with error Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='contentRef']/div/div[4]/button"}
  (Session info: chrome=145.0.7632.45); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ff721e94325
	0x7ff721e94380
	0x7ff721c2d49d
	0x7ff721c882fe
	0x7ff721c8860c
	0x7ff721cd8b67
	0x7ff721cd5728
	0x7ff721c78e38
	0x7ff721c79d23
	0x7ff722163090
	0x7ff72215d918
	0x7ff72217dc8a
	0x7ff721eb06d5
	0x7ff721eb967c
	0x7ff721e9d684
	0x7ff721e9d836
	0x7ff721e83347
	0x7ffd717ae8d7
	0x7ffd722cc40c

[85/2127] crawled: Jadenu 360 mg điều trị quá tải sắt mạn sau truyền máu ở thalassaemia (3 vỉ x 10 viên)
[86/2127] crawled: Arimidex 1mg điều trị hỗ trợ ung thư vú cho phụ nữ sau mãn kinh (2 vỉ x 14 viên)
[87/2127] crawled: Bột pha tiêm Herticad 150mg chỉ định điều trị ung thư vú di căn (MBC) hộp 1 lọ 150mg
[88/2127] crawled: Dung dịch tiêm Canpaxel 100mg/16.7ml điều trị ung thư buồng trứng, vú chai 16.7ml
[89/2127] crawled: Dung dịch pha tiêm Redditux 500mg/50ml điều trị u lympho, bạch cầu mạn chai 50ml
[90/2127] crawled: Dung dịch pha truyền Bestdocel 80mg/4ml điều trị ung thư vú, phổi chai 4ml
[91/2127] crawled: Equoral 25 mg dự phòng thải ghép sau ghép tạng (5 vỉ x 10 viên)
[92/2127] crawled: Regatonic hỗ trợ điều trị một số bệnh lý về mắt, cải thiện thị lực (6 vỉ x 10 viên)
[93/2127] crawled: Dung dịch tiêm Docetaxel Ebewe 20mg/2ml điều trị ung thư vú chai 2ml
[94/2127] crawled: Bột pha tiêm Winduza 100mg điều trị ung thư tủy xương, rối loạn tế bào máu hộp 1 lọ 100mg
[95/2127] crawled: Dung dịch tiêm Faslodex 250mg/5ml điều trị ung thư vú tiến xa tại chỗ (2 bơm tiêm x 5ml)
[96/2127] crawled: Dung dịch tiêm Avegra Biocad 400mg/16ml chỉ định điều trị ung thư vú di căn chai 16ml
[97/2127] crawled: Althax 120mg hỗ trợ điều trị viêm mũi dị ứng, nhiễm khuẩn hô hấp (3 vỉ x 10 viên)
[98/2127] crawled: Nolvadex 10mg chỉ định điều trị ung thư biểu mô tuyến vú (3 vỉ x 10 viên)
[99/2127] crawled: Cốm pha dung dịch uống Livact Granules giảm albumin máu (84 gói x 4.15g)
[100/2127] crawled: A.TZinC Siro 10mg/5ml hỗ trợ trị tiêu chảy, tăng đề kháng (30 ống x 5ml)
Saved 100 records to ankhang_medicines_data_demo.csv
[101/2127] crawled: Zedcal-OP Tablets trị loãng xương, nhuyễn xương (5 vỉ x 6 viên)
[102/2127] crawled: Dung dịch tiêm Bocartin 50mg/5ml điều trị ung thư buồng trứng, ung thư phổi chai 15ml
[103/2127] crawled: Dung dịch tiêm Peg-Grafeel 6mg/0.6ml điều trị hỗ trợ sau hóa xạ trị hộp 1 bơm tiêm 0.6ml
[104/2127] crawled: Seacaminfort 1500µg điều trị các bệnh lý thần kinh ngoại biên (10 vỉ x 10 viên)
[105/2127] crawled: Bột pha tiêm Gemita 1g điều trị ung thư di căn hoặc tiến triển lọ 1g
[106/2127] crawled: Sirô thuốc Glucozinc S bổ sung kẽm, trị thiếu kẽm (30 gói x 5ml)
[107/2127] failed: https://www.nhathuocankhang.com/thuoc-bo-va-vitamin/dung-dich-truyen-vitaplex-injection-chai-500ml?sku=1195280000012 with error Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='contentRef']/div/div[4]/button"}
  (Session info: chrome=145.0.7632.45); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ff721e94325
	0x7ff721e94380
	0x7ff721c2d49d
	0x7ff721c882fe
	0x7ff721c8860c
	0x7ff721cd8b67
	0x7ff721cd5728
	0x7ff721c78e38
	0x7ff721c79d23
	0x7ff722163090
	0x7ff72215d918
	0x7ff72217dc8a
	0x7ff721eb06d5
	0x7ff721eb967c
	0x7ff721e9d684
	0x7ff721e9d836
	0x7ff721e83347
	0x7ffd717ae8d7
	0x7ffd722cc40c

[108/2127] crawled: Dung dịch uống Stérogyl 2000000UI/100ml phòng và trị thiếu vitamin D chai 20ml
[109/2127] crawled: Hepedon Cap. 80mg hỗ trợ trị nhiễm khuẩn, kích thích miễn dịch (10 vỉ x 10 viên)
[110/2127] crawled: SilverZinc 50 phòng ngừa và trị thiếu kẽm (10 vỉ x 10 viên)
[111/2127] crawled: Dung dịch tiêm Human Albumin Baxter 200g/l phục hồi và duy trì thể tích máu chai 50ml
[112/2127] crawled: Neutri Fore trị viêm dây thần kinh, thiếu máu ác tính (10 vỉ x 10 viên)
[113/2127] crawled: L-Cystine Domesco 500mg trị rối loạn dưỡng tóc và móng (12 vỉ x 5 viên)
[114/2127] crawled: Exfast 25mg hỗ trợ điều trị ung thư vú (3 vỉ x 10 viên)
[115/2127] crawled: Dung dịch tiêm Neupogen 30MU/0.5ml điều trị giảm bạch cầu trung tính hộp 1 bơm tiêm 0.5ml
[116/2127] crawled: Tagrisso 80mg chỉ định điều trị ung thư tiến triển (1 vỉ x 10 viên)
[117/2127] crawled: Dung dịch pha tiêm Irinotecan Bidiphar 100mg/5ml điều trị ung thư biểu mô chai 5ml
[118/2127] crawled: Calquence 100mg điều trị u lympho tế bào vỏ, bạch cầu mạn dòng lympho (10 vỉ x 6 viên)
[119/2127] crawled: Tarceva 100mg điều trị ung thư phổi không tế bào nhỏ (3 vỉ x 10 viên)
[120/2127] crawled: Dung dịch tiêm Alexan 500mg/10ml điều trị bệnh bạch cầu dòng tủy cấp tính chai 10ml
[121/2127] crawled: Dung dịch tiêm Humira 40mg/0.4ml điều trị viêm khớp dạng thấp (2 bơm tiêm x 0.4ml)
[122/2127] crawled: Dung dịch tiêm Avegra Biocad 100mg/4ml chỉ định điều trị ung thư vú di căn chai 4ml
[123/2127] crawled: Ofev 100mg điều trị ung thư phổi không tế bào nhỏ (6 vỉ x 10 viên)
[124/2127] crawled: Ofev 150mg điều trị ung thư phổi không tế bào nhỏ (6 vỉ x 10 viên)
[125/2127] failed: https://www.nhathuocankhang.com/thuoc-bo-va-vitamin/vitamin-a-d-5000ui-400ui-hd-100v?sku=1193668000844 with error Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='contentRef']/div/div[4]/button"}
  (Session info: chrome=145.0.7632.45); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ff721e94325
	0x7ff721e94380
	0x7ff721c2d49d
	0x7ff721c882fe
	0x7ff721c8860c
	0x7ff721cd8b67
	0x7ff721cd5728
	0x7ff721c78e38
	0x7ff721c79d23
	0x7ff722163090
	0x7ff72215d918
	0x7ff72217dc8a
	0x7ff721eb06d5
	0x7ff721eb967c
	0x7ff721e9d684
	0x7ff721e9d836
	0x7ff721e83347
	0x7ffd717ae8d7
	0x7ffd722cc40c

[126/2127] crawled: Lenvima 4mg chỉ định điều trị ung thư tuyến giảp, ung thư biểu mô (2 vỉ x 10 viên)
[127/2127] crawled: Tagrisso 40mg điều trị ung thư phổi không tế bào nhỏ di căn (1 vỉ x 30 viên)
[128/2127] crawled: Certican 0.5mg dự phòng thải tạng ghép ở bệnh nhân ghép thận hoặc tim (6 vỉ x 10 viên)
[129/2127] crawled: Alecensa cap 150 mg điều trị ung thư phổi không tế bào nhỏ (4 hộp x 56 viên)
[130/2127] crawled: Dịch truyền Natri Clorid 0,9% Fresenius Kabi bổ sung muối và nước chai 100ml
[131/2127] crawled: Bút tiêm Saxenda 6mg/ml giảm cân nặng, hỗ trợ cho chế độ ăn giảm calo (3 cây x 3ml)
[132/2127] crawled: Unitrexates 2.5mg điều trị các bệnh ung thư, viêm khớp dạng thấp (10 vỉ x 10 viên)
[133/2127] crawled: Dung dịch tiêm Perjeta 420mg/14ml điều trị ung thư di căn, ung thư vú chai 14ml
[134/2127] crawled: Nexavar 200mg điều trị ung thư tế bào biểu mô (6 vỉ x 10 viên)
[135/2127] crawled: Prograf 1mg phòng ngừa thải ghép ở bệnh nhân ghép thận hoặc gan (5 vỉ x 10 viên)
[136/2127] crawled: Dung dịch tiêm truyền Glucose 5% Fresenius Kabi điều trị hạ đường huyết chai 500ml
[137/2127] failed: https://www.nhathuocankhang.com/thuoc-bo-va-vitamin/savprocal-d-750mg-200ui-h30v?sku=1193668000843 with error Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='contentRef']/div/div[4]/button"}
  (Session info: chrome=145.0.7632.45); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ff721e94325
	0x7ff721e94380
	0x7ff721c2d49d
	0x7ff721c882fe
	0x7ff721c8860c
	0x7ff721cd8b67
	0x7ff721cd5728
	0x7ff721c78e38
	0x7ff721c79d23
	0x7ff722163090
	0x7ff72215d918
	0x7ff72217dc8a
	0x7ff721eb06d5
	0x7ff721eb967c
	0x7ff721e9d684
	0x7ff721e9d836
	0x7ff721e83347
	0x7ffd717ae8d7
	0x7ffd722cc40c

[138/2127] failed: https://www.nhathuocankhang.com/thuoc-bo-va-vitamin/furagon-hop-100-vien?sku=1193690000192 with error Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='contentRef']/div/div[4]/button"}
  (Session info: chrome=145.0.7632.45); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ff721e94325
	0x7ff721e94380
	0x7ff721c2d49d
	0x7ff721c882fe
	0x7ff721c8860c
	0x7ff721cd8b67
	0x7ff721cd5728
	0x7ff721c78e38
	0x7ff721c79d23
	0x7ff722163090
	0x7ff72215d918
	0x7ff72217dc8a
	0x7ff721eb06d5
	0x7ff721eb967c
	0x7ff721e9d684
	0x7ff721e9d836
	0x7ff721e83347
	0x7ffd717ae8d7
	0x7ffd722cc40c

[139/2127] crawled: Thuốc tiêm Eranfu 250mg/5ml điều trị ung thư vú ở phụ nữ sau mãn kinh (2 bơm tiêm x 5ml)
[140/2127] crawled: Bột pha tiêm Bigemax 1g điều trị ung thư phổi, ung thư tụy hộp 1 lọ 1g
[141/2127] crawled: Dung dịch tiêm Mabthera 100mg/10ml điều trị u lympho, u hạt (2 chai x 10ml)
[142/2127] crawled: Capbize 500mg điều trị ung thư vú, ung thư dạ dày (3 vỉ x 10 viên)
[143/2127] crawled: Dung dịch tiêm Epirubicin Ebewe 50mg/25ml điều trị ung thư vú chai 25ml
[144/2127] crawled: Iressa 250mg điều trị ung thư phổi loại không phải tế bào nhỏ (3 vỉ x 10 viên)
[145/2127] crawled: Citropholi 500mg tăng cường hệ miễn dịch (10 vỉ x 10 viên)
[146/2127] crawled: Bột pha tiêm Herceptin 150mg điều trị ung thư vú hộp 1 lọ 150mg
[147/2127] crawled: Dung dịch tiêm Actemra 162mg/0.9ml điều trị viêm khớp dạng thấp (4 bơm tiêm x 0.9ml)
[148/2127] crawled: Ibrance 100mg Pfizer chỉ định điều trị một số trường hợp ung thư vú (1 vỉ x 7 viên)
[149/2127] crawled: Dung dịch tiêm truyền Ringer Lactate bù nước và điện giải chai 500ml
[150/2127] crawled: Dung dịch tiêm Doxorubicin Ebewe 10mg/5ml điều trị u cứng, ung thư máu chai 5ml
Saved 150 records to ankhang_medicines_data_demo.csv
[151/2127] crawled: Imatinib Teva 100mg dùng trong điều trị ung thư bạch cầu tuỷ mạn (12 vỉ x 10 viên)
[152/2127] crawled: Navelbine 30 đơn điều trị liệu hoặc kết hợp hóa điều trị điều trị ung thư vú (1 vỉ x 1 viên)
[153/2127] crawled: Dung dịch tiêm Mabthera 1400mg/11.7ml điều trị u lympho, u hạt chai 11.7ml
[154/2127] crawled: Semozine 80mg tăng cường miễn dịch, hỗ trợ trị nhiễm khuẩn hô hấp (6 vỉ x 10 viên)
[155/2127] crawled: Kryxana 200mg chỉ định trong điều trị một số thể ung thư vú (1 vỉ x 21 viên)
[156/2127] crawled: Dung dịch tiêm Lyoxatin 100mg/20ml chỉ định trong điều trị ung thư đại tràng chai 20ml
[157/2127] crawled: Dung dịch Bendamustine Hydrochloride 180mg/4ml chỉ định điều trị ung thư chai 4ml
[158/2127] crawled: Tagrisso 80mg chỉ định điều trị ung thư tiến triển (3 vỉ x 10 viên)
[159/2127] crawled: Femara 2.5mg điều trị bổ trợ ung thư vú (3 vỉ x 10 viên)

In [10]:
ankhang_medicine_data = pd.read_csv("ankhang_medicines_data_demo.csv")
ankhang_medicine_data.head(10)

,ten_thuoc,gia,hinh_anh,cong_dung_tom_tat,thanh_phan_chinh,doi_tuong,thuong_hieu,noi_san_xuat,dang_bao_che,han_dung,thanh_phan_chi_tiet,cong_dung_chi_tiet,cach_dung,chong_chi_dinh,tac_dung_phu,luu_y,url,category,drug_type,error
0,"Timi Roitin trị viêm dây thần kinh, thoái hóa ...",528.000₫,https://cdn.tgdd.vn/Products/Images/10053/1304...,"Bổ sung vitamin nhóm B, điều trị viêm dây thần...","Chondroitin, Vitamin B5, Fursultiamine, Vitami...",Người lớn,Phil Inter Pharma,Việt Nam,Viên nang mềm,36 tháng kể từ ngày sản xuất,"Hoạt chất: Chondroitin sulfate natri 90mg, Nic...",- Bổ sung các vitamin nhóm B trong các trường ...,Người lớn: Uống 1 viên/ngày.\n- Quá liều\nDùng...,- Quá mẫn với bất cứ thành phần nào của thuốc....,TIMIROITIN thường được dung nạp tốt khi dùng ở...,- Thận trọng khi sử dụng\n- Khi sử dụng nicoti...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
1,B Complex C bổ sung vitamin nhóm B và vitamin ...,800₫,https://cdn.tgdd.vn/Products/Images/10053/1295...,Dự phòng & bổ sung khi thiếu hụt các vitamin n...,"Vitamin PP, Vitamin C, Vitamin B6, Vitamin B2,...",NaN,Vidipha,Việt Nam,Viên nang cứng,24 tháng kể từ ngày sản xuất,"Hoạt chất: Vitamin B1 15mg, Vitamin B2 10mg, V...",B Complex C dự phòng và bổ sung thiếu hụt các ...,Liều lượng: Trung bình: 1 - 2 viên/ngày.\nCách...,Dị ứng với một trong các thành phần của thuốc....,Dùng liều cao nước tiểu sẽ có màu vàng nhạt (d...,- Thận trọng khi sử dụng\nKhi sử dụng nicotina...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,NaN,NaN,Message: no such element: Unable to locate ele...
3,Vitamin PP 50 Pharmedic ngăn ngừa thiếu nicoti...,12.000₫,https://cdn.tgdd.vn/Products/Images/10053/1533...,Bổ sung vào khẩu phần ăn để ngăn ngừa thiếu hụ...,Vitamin PP,Người lớn và trẻ em trên 5 tuổi,Pharmedic,Việt Nam,Viên nén,NaN,Nicotinamid 50mg.\nTá dược 1 viên.,Vitamin PP 50 giúp bổ sung vào khẩu phần ăn để...,"Người lớn: mỗi lần 1 - 2 viên, ngày 3 lần.\nTr...","- Dị ứng với nicotinamid.\n- Bệnh gan nặng, lo...",NaN,- Thận trọng khi sử dụng\nNgười có tiền sử loé...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
4,"Agi-Calci bổ sung canxi, trị loãng xương (20 v...",150.000₫,https://cdn.tgdd.vn/Products/Images/10053/2463...,Bổ sung calci khi thiếu hay tăng nhu cầu calci...,"Calci cacbonat, Vitamin D3",NaN,Agimexpharm,Việt Nam,Viên nén bao phim,24 tháng kể từ ngày sản xuất,Mỗi viên nén bao phim chứa:\nHoạt chất: Calci ...,- Agi-Calci bổ sung calci trong các trường hợp...,Uống thuốc buổi sáng hoặc buổi trưa theo liều ...,"- Tăng calci huyết, calci niệu, sỏi calci, suy...",- Dùng thuốc chứa muối calci qua đường uống có...,- Thận trọng khi sử dụng\nThận trọng khi sử dụ...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
5,Vitamin B1 Mekophar 250mg trị các bệnh thiếu v...,7.000₫,https://cdn.tgdd.vn/Products/Images/10053/1535...,"Điều trị các bệnh do thiếu B1, suy nhược cơ th...",NaN,NaN,Mekophar,Việt Nam,Viên nén bao đường,36 tháng kể từ ngày sản xuất,Hoạt chất: Thiamine nitrate (vitamin B1) 250mg...,- Điều trị các bệnh do thiếu vitamin B1 như: b...,- Theo chỉ dẫn của bác sĩ.\n- Người lớn: uống ...,Quá mẫn với một trong các thành phần của thuốc.,"- Tác dụng phụ rất hiếm khi xảy ra như: ngứa, ...",- Thận trọng khi sử dụng\nThận trọng khi sử dụ...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
6,Dung dịch uống Calciumboston Ascorbic trị thiế...,9.100₫,"https://img.tgdd.vn/imgt/ankhang/f_webp,fit_ou...","Điều trị các tình trạng thiếu calci, vitamin C...","Vitamin PP, Vitamin C, Calci glucoheptonat",Người lớn và trẻ em,Boston Pharma,Việt Nam,Dung dịch,36 tháng kể từ ngày sản xuất,Hoạt chất: Mỗi ml dung dịch thuốc chứa:\n- Cal...,Điều trị các tình trạng thiếu vitamin C và Vit...,- Cách dùng\nCalciumboston Ascorbic được dùng ...,Quá mẫn với bất kỳ thành phần nào của thuốc.\n...,Hệ cơ quan\nTần suất\nTác dụng phụ\n\n\n\nHệ t...,NaN,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
7,"Viên Hà Thủ Ô Extracap trị suy nhược, tóc bạc ...",70.000₫,https://cdn.tgdd.vn/Products/Images/10053/1527...,"Trị tinh tủy kém, thần kinh suy nhược ở nam gi...",Hà thủ ô đỏ,NaN,Dược phẩm OPC,Việt Nam,Viên nang cứng,36 tháng kể từ ngày sản xuất,Hoạt chất: Cao đặc qui về khan 340mg [Tương ứn...,"Nam giới tinh tủy kém, thần kinh suy nhược.\nD...","Uống mỗi lần 2 viên, ngày 3 lần. Uống trước bữ...",Không dùng cho phụ nữ có thai.\nKhông dùng cho...,Chưa có báo cáo.\nThông báo cho bác sĩ những t...,- Thận trọng khi sử dụng\nChưa có báo cáo.\n- ...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
8,"Hỗn dịch uống Zedcal bổ sung canxi, magie, kẽm...",79.000₫,https://cdn.tgdd.vn/Products/Images/10053/1303...,"Bổ sung canxi, vitamin D3","Calcium, Vitamin D3, Magnesium, Kẽm",Trẻ em cần bổ sung canxi,Meyer,Ấn Độ,Siro,36 tháng kể từ khi sản xuất,Mỗi 5ml chứa:\nCalcium carbonate B.P tương đươ...,Zedcal là một dạng thuốc dùng bổ sung calci và...,Trẻ em: (1 - 3 tuổi) 5ml/lần x 1 lần mỗi ngày....,Chống chỉ định với bệnh nhân quá mẫn với bất k...,Thuốc này thì an toàn và gần như không gây tác...,- Thận trọng khi sử dụng\nZedcal không nên dùn...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
9,"Franvit C.Ex 500 bổ sung vitamin C, tăng đề kh...",57.500₫,https://cdn.tgdd.vn/Products/Images/10053/2492...,"Phòng và điều trị bệnh do thiếu Vitamin C, phò...",Acid Ascorbic,NaN,Éloge France Việt Nam,Việt Nam,Viên nén,24 tháng kể từ ngày sản xuất,Hoạt chất: Acid Ascorbic 500 mg.\nTá dược: Tin...,- Phòng và điều trị bệnh do thiếu Vitamin C.\n...,Uống sau bữa ăn.\n- Bệnh thiếu Vitamin C:\nNgư...,Người bị thiếu hụt G6PD (nguy cơ thiếu máu tan...,"Tăng oxalat niệu, buồn nôn, nôn, ợ nóng, co cứ...",- Thận trọng khi sử dụng\n- Dùng thuốc này kéo...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN

In [12]:
# Lấy nhưng dòng bị lỗi crawl lại
error_rows = ankhang_medicine_data[ankhang_medicine_data['ten_thuoc'].isnull() | ankhang_medicine_data['ten_thuoc'].isna()]
print(f"Số dòng bị lỗi: {error_rows.shape[0]}")
error_rows.head()

Số dòng bị lỗi: 54

,ten_thuoc,gia,hinh_anh,cong_dung_tom_tat,thanh_phan_chinh,doi_tuong,thuong_hieu,noi_san_xuat,dang_bao_che,han_dung,thanh_phan_chi_tiet,cong_dung_chi_tiet,cach_dung,chong_chi_dinh,tac_dung_phu,luu_y,url,category,drug_type,error
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,NaN,NaN,Message: no such element: Unable to locate ele...
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,NaN,NaN,Message: no such element: Unable to locate ele...
83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-tri-ung-...,NaN,NaN,Message: no such element: Unable to locate ele...
106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,NaN,NaN,Message: no such element: Unable to locate ele...
124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,NaN,NaN,Message: no such element: Unable to locate ele...

In [13]:
error_rows.to_csv("ankhang_medicines_error_rows.csv", index=False, encoding='utf-8-sig')