In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
# Đọc file Long Châu đã xử lý
df_preprocessed = pd.read_csv("Longchau_data_processed.csv")
df_preprocessed.shape
df_preprocessed

,url,ten_thuoc,gia,hinh_anh,thanh_phan,cong_dung,chong_chi_dinh,lieu_dung,luu_y,tac_dung_phu,bao_quan,mo_ta
0,https://nhathuoclongchau.com.vn/thuoc/5-fluoro...,Thuốc 5-Fluorouracil 50mg Novartis điều trị gi...,NaN,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,[Fluorouracil 50mg/ml],[Dung dịch pha tiêm 5-Fluorouracil Ebewe chỉ đ...,[Dung dịch pha tiêm 5-Fluorouracil Ebewe chống...,"[Khởi đầu điều trị Hàng ngày dùng như sau, Tru...",[Trước khi sử dụng thuốc bạn cần đọc kỹ hướng ...,[Khi sử dụng dung dịch pha tiêm 5-Fluorouracil...,[Không bảo quản trên 25C. Không để đông lạnh. ...,[Thuốc 5-Fluorouracil Ebewe là dung dịch đậm đ...
1,https://nhathuoclongchau.com.vn/thuoc/actadol-...,Thuốc Actadol 500 Medipharco điều trị các chứn...,500.0,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,[Paracetamol 500mg],[Paracetamol được dùng rộng rãi trong điều trị...,[Thuốc Actadol chống chỉ định trong các trường...,[Người lớn và trẻ em trên 11 tuổi Uống 1 viên/...,[Trước khi sử dụng thuốc bạn cần đọc kỹ hướng ...,[Khi sử dụng Actadol thường gặp các tác dụng k...,"[Để nơi mát, tránh ánh sáng, nhiệt độ dưới 30⁰...",[Thuốc Actadol là sản phẩm của Công ty Cổ phần...
2,https://nhathuoclongchau.com.vn/thuoc/allerpha...,Thuốc Allerphast 180mg Mebiphar điều trị viêm ...,2.5,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,[Fexofenadin Hydroclorid 180mg],[Allerphast được chỉ định sử dụng trong trường...,[Allerphast chống chỉ định trong các trường hợ...,"[Viêm mũi dị ứng, Người lớn và trẻ em trên 12 ...",[Chống chỉ địnhAllerphast chống chỉ định trong...,[Khi sử dụng Allerphast 180 mg thường gặp các ...,"[Tránh ánh sáng và ẩm, nhiệt độ dưới 30oC., Th...",[Allerphast 180 mg là một sản phẩm của công ty...
3,https://nhathuoclongchau.com.vn/thuoc/ambroxol...,"Siro Ambroxol Danapha điều trị viêm phế quản, ...",30.0,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,[Ambroxol hydroclorid 0.3% (kl/tt)],[Thuốc Sirô Ambroxol được chỉ định dùng trong ...,[Thuốc Ambroxol Danapha chống chỉ định trong c...,"[Trẻ em 2 - 5 tuổi2,5ml x 3 lần/ngày., Trẻ em ...",[Trước khi sử dụng thuốc bạn cần đọc kỹ hướng ...,[Khi sử dụng thuốc Sirô Ambroxol bạn có thể gặ...,"[Bảo quản nơi khô mát, tránh ánh sáng, nhiệt đ...",[Thuốc siro Ambroxol là sản phẩm của Dược Dana...
4,https://nhathuoclongchau.com.vn/thuoc/agiclovi...,Thuốc mỡ bôi da Agiclovir 5% Agimexpharm điều ...,10.0,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,"[Aciclovir 0.25g, Excipients q.s 5g]",[Thuốc mỡ bôi da Agiclovir 5%được chỉ định dùn...,[Thuốc mỡ bôi da Agiclovir 5% chống chỉ định t...,"[Thoa thuốc lên vùng da bị nhiễm, 5 - 6 lần/mỗ...",[Trước khi sử dụng thuốc bạn cần đọc kỹ hướng ...,"[Khi sử dụng thuốc mỡ bôi da Agiclovir 5%, bạn...","[Để ở nhiệt độ dưới 30C, tránh ẩm và ánh sáng....",[Thuốc mỡ bôi da Agiclovir 5% là sản phẩm của ...
...,...,...,...,...,...,...,...,...,...,...,...,...
5667,https://nhathuoclongchau.com.vn/thuoc/zedcal-1...,Siro Zedcal Meyer bổ sung canxi và thiếu hụt v...,NaN,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,"[Calcium 150mg, Kẽm 2mg, Vitamin D3 200IU, Mag...",[Zedcal 100 ml được chỉ định dùng cho các trườ...,[Zedcal 100 ml chống chỉ định trong trường hợp...,"[Trẻ em 0 - 3 tuổi, 5 ml/lần x 1 lần mỗi ngày....",[Chống chỉ địnhZedcal 100 ml chống chỉ định tr...,[Thuốc này an toàn và gần như không gây tác dụ...,"[Bảo quản dưới 30oC, nơi khô thoáng. Tránh ánh...",[Zedcal 100 ml là sản phẩm của Công ty Meyer H...
5668,https://nhathuoclongchau.com.vn/thuoc/zt-amox-...,Bột pha hỗn dịch uống ZT-Amox 200/28.5mg Bilim...,NaN,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,"[Amoxicillin 200mg, Clavulanic acid 28.5mg]",[Thuốc Zt - Amox 200/28.5 mg Bilim 70 ml được ...,[Thuốc Zt - Amox 200/28.5 mg Bilim 70 ml chống...,"[Nhiễm khuẩn nhẹ đến trung bình 25/3,6 mg (amo...",[Trước khi sử dụng thuốc bạn cần đọc kỹ hướng ...,[Khi sử dụng thuốc Zt - Amox 200/28.5 mg Bilim...,"[Bảo quản ở nơi khô, dưới 30C., Bột pha hỗn dị...",[Zt - Amox 200/28.5 mg có quy cách đóng gói gồ...
5669,https://nhathuoclongchau.com.vn/thuoc/zantagel...,Hỗn dịch Zantagel Susp JS Pharm điều trị đau c...,NaN,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,"[Oxethazaine 20mg, Nhôm hydroxyd 582mg, Magnes...",[Thuốc Zantagel được chỉ định dùng trong các t...,[Thuốc Zantagel chống chỉ định trong các trườn...,"[Uống 1/2 gói - 1 gói, ngày 3 - 4 lần., Không ...",[Trước khi sử dụng thuốc bạn cần đọc kỹ hướng ...,"[Khi sử dụng thuốc Zantagel Susp Js, bạn có th...","[Bảo quản trong bao bì kín, tránh ánh sáng, ở ...",[Zantagel được sản xuất bởi JS Pharm. Co]
5670,https://nhathuoclongchau.com.vn/thuoc/zidotex-...,Dung dịch Zidotex 100mg Hataphar điều trị rối ...,NaN,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,[Citicoline 1],[Thuốc Zidotex chỉ định điều trị trong các trư...,[Thuốc Zidotex chống chỉ định trong các trường...,"[Người lớn Dùng liều 100 - 200mg (1 - 2 ml), h...",[Trước khi sử dụng thuốc bạn cần đọc kỹ hướng ...,[Thuốc Zidotex thường gặp các tác dụng không m...,"[Để nơi mát, tránh ánh sáng, nhiệt độ dưới 30⁰...",[Thuốc Zidotex là sản phẩm của Hataphar chứa C...
5671,https://nhathuoclongchau.com.vn/thuoc/zaromax-...,Thuốc Zaromax 250 DHG điều trị nhiễm khuẩn đườ...,NaN,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,[Azithromycin 250mg],[Thuốc Zaromax 250 được chỉ định dùng trong cá...,[Thuốc Zaromax 250 chống chỉ định trong các tr...,"[Nhiễm khuẩn đường hô hấp trên và dưới, nhiễm ...",[Trước khi sử dụng thuốc bạn cần đọc kỹ hướng ...,[Khi sử dụng thuốc Zaromax 250 thường gặp các ...,"[Nơi khô, nhiệt độ không quá 30oC, tránh ánh s...",[Thuốc Zaromax 250 là viên nén chứa hoạt chất ...

In [11]:
# Đọc file Category mới cào thêm
df_category = pd.read_csv(r"D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_LongChau\longchau_medicine_category_links(3).csv")
df_category.shape
df_category.head()

,Category Name,Category Link,Medicine Link
0,Thuốc dị ứng\n138 sản phẩm,https://nhathuoclongchau.com.vn/thuoc/thuoc-di...,https://nhathuoclongchau.com.vn/thuoc/exopadin...
1,Thuốc dị ứng\n138 sản phẩm,https://nhathuoclongchau.com.vn/thuoc/thuoc-di...,https://nhathuoclongchau.com.vn/thuoc/cetirizi...
2,Thuốc dị ứng\n138 sản phẩm,https://nhathuoclongchau.com.vn/thuoc/thuoc-di...,https://nhathuoclongchau.com.vn/thuoc/allerpha...
3,Thuốc dị ứng\n138 sản phẩm,https://nhathuoclongchau.com.vn/thuoc/thuoc-di...,https://nhathuoclongchau.com.vn/thuoc/histalon...
4,Thuốc dị ứng\n138 sản phẩm,https://nhathuoclongchau.com.vn/thuoc/thuoc-di...,https://nhathuoclongchau.com.vn/thuoc/vomina-p...

In [7]:
df_combined = df_preprocessed.merge(
    df_category[['Medicine Link', 'Category Name', 'Category Link']], 
    left_on='url',  # tên cột trong df_preprocessed (thay 'url' nếu khác)
    right_on='Medicine Link',  # tên cột trong df_category
    how='left'
)

missing = df_combined['Category Name'].isna().sum()
print(f"Số lượng thuốc không tìm thấy category: {missing}")

df_combined.to_csv("Longchau_data_with_category.csv", index=False)

Số lượng thuốc không tìm thấy category: 91

In [2]:
df_new = pd.read_csv("Longchau_data_with_category.csv", encoding='utf')
print(df_new.shape)
df_new.head()

(5672, 15)

,url,ten_thuoc,gia,hinh_anh,thanh_phan,cong_dung,chong_chi_dinh,lieu_dung,luu_y,tac_dung_phu,bao_quan,mo_ta,Medicine Link,Category Name,Category Link
0,https://nhathuoclongchau.com.vn/thuoc/5-fluoro...,Thuốc 5-Fluorouracil 50mg Novartis điều trị gi...,NaN,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,[Fluorouracil 50mg/ml],[Dung dịch pha tiêm 5-Fluorouracil Ebewe chỉ đ...,[Dung dịch pha tiêm 5-Fluorouracil Ebewe chống...,"[Khởi đầu điều trị Hàng ngày dùng như sau, Tru...",[Trước khi sử dụng thuốc bạn cần đọc kỹ hướng ...,[Khi sử dụng dung dịch pha tiêm 5-Fluorouracil...,[Không bảo quản trên 25C. Không để đông lạnh. ...,[Thuốc 5-Fluorouracil Ebewe là dung dịch đậm đ...,https://nhathuoclongchau.com.vn/thuoc/5-fluoro...,Thuốc ung thư\n148 sản phẩm,https://nhathuoclongchau.com.vn/thuoc/thuoc-di...
1,https://nhathuoclongchau.com.vn/thuoc/actadol-...,Thuốc Actadol 500 Medipharco điều trị các chứn...,500.0,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,[Paracetamol 500mg],[Paracetamol được dùng rộng rãi trong điều trị...,[Thuốc Actadol chống chỉ định trong các trường...,[Người lớn và trẻ em trên 11 tuổi Uống 1 viên/...,[Trước khi sử dụng thuốc bạn cần đọc kỹ hướng ...,[Khi sử dụng Actadol thường gặp các tác dụng k...,"[Để nơi mát, tránh ánh sáng, nhiệt độ dưới 30⁰...",[Thuốc Actadol là sản phẩm của Công ty Cổ phần...,https://nhathuoclongchau.com.vn/thuoc/actadol-...,"Thuốc giảm đau, hạ sốt, kháng viêm\n383 sản phẩm",https://nhathuoclongchau.com.vn/thuoc/thuoc-gi...
2,https://nhathuoclongchau.com.vn/thuoc/allerpha...,Thuốc Allerphast 180mg Mebiphar điều trị viêm ...,2.5,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,[Fexofenadin Hydroclorid 180mg],[Allerphast được chỉ định sử dụng trong trường...,[Allerphast chống chỉ định trong các trường hợ...,"[Viêm mũi dị ứng, Người lớn và trẻ em trên 12 ...",[Chống chỉ địnhAllerphast chống chỉ định trong...,[Khi sử dụng Allerphast 180 mg thường gặp các ...,"[Tránh ánh sáng và ẩm, nhiệt độ dưới 30oC., Th...",[Allerphast 180 mg là một sản phẩm của công ty...,https://nhathuoclongchau.com.vn/thuoc/allerpha...,Thuốc dị ứng\n138 sản phẩm,https://nhathuoclongchau.com.vn/thuoc/thuoc-di...
3,https://nhathuoclongchau.com.vn/thuoc/ambroxol...,"Siro Ambroxol Danapha điều trị viêm phế quản, ...",30.0,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,[Ambroxol hydroclorid 0.3% (kl/tt)],[Thuốc Sirô Ambroxol được chỉ định dùng trong ...,[Thuốc Ambroxol Danapha chống chỉ định trong c...,"[Trẻ em 2 - 5 tuổi2,5ml x 3 lần/ngày., Trẻ em ...",[Trước khi sử dụng thuốc bạn cần đọc kỹ hướng ...,[Khi sử dụng thuốc Sirô Ambroxol bạn có thể gặ...,"[Bảo quản nơi khô mát, tránh ánh sáng, nhiệt đ...",[Thuốc siro Ambroxol là sản phẩm của Dược Dana...,https://nhathuoclongchau.com.vn/thuoc/ambroxol...,Thuốc hô hấp\n310 sản phẩm,https://nhathuoclongchau.com.vn/thuoc/thuoc-ho...
4,https://nhathuoclongchau.com.vn/thuoc/agiclovi...,Thuốc mỡ bôi da Agiclovir 5% Agimexpharm điều ...,10.0,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,"[Aciclovir 0.25g, Excipients q.s 5g]",[Thuốc mỡ bôi da Agiclovir 5%được chỉ định dùn...,[Thuốc mỡ bôi da Agiclovir 5% chống chỉ định t...,"[Thoa thuốc lên vùng da bị nhiễm, 5 - 6 lần/mỗ...",[Trước khi sử dụng thuốc bạn cần đọc kỹ hướng ...,"[Khi sử dụng thuốc mỡ bôi da Agiclovir 5%, bạn...","[Để ở nhiệt độ dưới 30C, tránh ẩm và ánh sáng....",[Thuốc mỡ bôi da Agiclovir 5% là sản phẩm của ...,https://nhathuoclongchau.com.vn/thuoc/agiclovi...,"Thuốc kháng sinh, kháng nấm\n561 sản phẩm",https://nhathuoclongchau.com.vn/thuoc/thuoc-kh...