In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# Data Điều trị
DieuTri_df = pd.read_csv(r'D:\OU\KhoaLuanTotNghiep\DrugRecommandation\preprocessData_DieuTri\DieuTri_processed.csv')
print("Số dòng và số cột của DataFrame: ", DieuTri_df.shape)
print("Các cột trong DataFram Điều trị: ", DieuTri_df.columns)
DieuTri_df.head()

Số dòng và số cột của DataFrame:  (1008, 12)
Các cột trong DataFram Điều trị:  Index(['Tên thuốc', 'link', 'Chỉ định', 'Thành phần', 'Liều dùng', 'Cách dùng',
       'Tác dụng phụ', 'Chống chỉ định', 'Thận trọng', 'Cảnh báo',
       'Tương tác thuốc', 'Mang thai và cho con bú'],
      dtype='object')

,Tên thuốc,link,Chỉ định,Thành phần,Liều dùng,Cách dùng,Tác dụng phụ,Chống chỉ định,Thận trọng,Cảnh báo,Tương tác thuốc,Mang thai và cho con bú
0,Azelastine: thuốc điều trị viêm mũi,https://www.dieutri.vn/a/azelastine-thuoc-dieu...,NaN,NaN,"Thuốc xịt mũi 0,1% (137mcg / lần xịt). 0,15% (...",NaN,Các tác dụng phụ thường gặp Vị đắng trong miện...,Quá mẫn đã được ghi nhận.,Có thể gây suy nhược thần kinh trung ương / bu...,NaN,Azelastine có tương tác nghiêm trọng với các l...,Dữ liệu hạn chế từ kinh nghiệm sau khi đưa thu...
1,Axit acetohydroxamic: thuốc điều trị nhiễm trù...,https://www.dieutri.vn/a/axit-acetohydroxamic-...,NaN,NaN,NaN,NaN,Tác dụng phụ thường gặp Đau đầu nhẹ; 48 giờ đầ...,Quá mẫn cảm. Bệnh nhân thích nghi với phẫu thu...,Luôn sử dụng cùng với điều trị kháng sinh thíc...,Thuốc này chứa axit acetohydroxamic. Không dùn...,Axit acetohydroxamic không có tương tác nghiêm...,Không sử dụng axit acetohydroxamic trong thai ...
2,Axalimogene Filolisbac: thuốc điều trị ung thư...,https://www.dieutri.vn/a/axalimogene-filolisba...,NaN,NaN,Axalimogene filolisbac đang trong quá trình th...,NaN,Mệt mỏi. Ớn lạnh. Sốt. Buồn nôn. Đau đầu. Hạ h...,Không có thông tin.,Không có thông tin.,Thuốc này chứa axalimogene filolisbac. Không d...,Axalimogene filolisbac đang trong quá trình th...,Axalimogene filolisbac đang trong quá trình th...
3,Avelumab: thuốc điều trị ung thư,https://www.dieutri.vn/a/avelumab-thuoc-dieu-t...,NaN,NaN,Thuốc tiêm: 20mg / ml (lọ đơn liều 200mg / 10m...,NaN,Viêm tụy. Viêm cơ tim. Viêm cơ. Suy tim sung h...,Không có.,Độc tính trên phôi thai có thể xảy ra dựa trên...,Thuốc này có chứa avelumab. Không dùng Bavenci...,Avelumab không có tương tác nghiêm trọng được ...,"Dựa trên cơ chế hoạt động của nó, có thể gây h..."
4,Atovaquone Proguanil: thuốc điều trị sốt rét,https://www.dieutri.vn/a/atovaquone-proguanil-...,NaN,NaN,NaN,NaN,"Không có. Đau dạ dày, Ăn mất ngon, Mệt mỏi, Ng...",Quá mẫn cảm. Dự phòng ở người suy thận nặng (C...,Sử dụng thuốc này không là một phương pháp chữ...,NaN,Atovaquone / Proguanil có những tương tác nghi...,Thận trọng khi sử dụng nếu lợi ích mang lại nh...

In [3]:
# Data Long Châu
LongChau_df = pd.read_csv(r'D:\OU\KhoaLuanTotNghiep\DrugRecommandation\preprocessData_LongChau\Longchau_data_processed.csv')
print("Số dòng và số cột của DataFrame: ", LongChau_df.shape)
print("Các cột trong DataFrame Long Châu: ", LongChau_df.columns)
LongChau_df.head()

Số dòng và số cột của DataFrame:  (5672, 12)
Các cột trong DataFrame Long Châu:  Index(['url', 'ten_thuoc', 'gia', 'hinh_anh', 'thanh_phan', 'cong_dung',
       'chong_chi_dinh', 'lieu_dung', 'luu_y', 'tac_dung_phu', 'bao_quan',
       'mo_ta'],
      dtype='object')

,url,ten_thuoc,gia,hinh_anh,thanh_phan,cong_dung,chong_chi_dinh,lieu_dung,luu_y,tac_dung_phu,bao_quan,mo_ta
0,https://nhathuoclongchau.com.vn/thuoc/5-fluoro...,Thuốc 5-Fluorouracil 50mg Novartis điều trị gi...,NaN,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,[Fluorouracil 50mg/ml],[Dung dịch pha tiêm 5-Fluorouracil Ebewe chỉ đ...,[Dung dịch pha tiêm 5-Fluorouracil Ebewe chống...,"[Khởi đầu điều trị Hàng ngày dùng như sau, Tru...",[Trước khi sử dụng thuốc bạn cần đọc kỹ hướng ...,[Khi sử dụng dung dịch pha tiêm 5-Fluorouracil...,[Không bảo quản trên 25C. Không để đông lạnh. ...,[Thuốc 5-Fluorouracil Ebewe là dung dịch đậm đ...
1,https://nhathuoclongchau.com.vn/thuoc/actadol-...,Thuốc Actadol 500 Medipharco điều trị các chứn...,500.0,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,[Paracetamol 500mg],[Paracetamol được dùng rộng rãi trong điều trị...,[Thuốc Actadol chống chỉ định trong các trường...,[Người lớn và trẻ em trên 11 tuổi Uống 1 viên/...,[Trước khi sử dụng thuốc bạn cần đọc kỹ hướng ...,[Khi sử dụng Actadol thường gặp các tác dụng k...,"[Để nơi mát, tránh ánh sáng, nhiệt độ dưới 30⁰...",[Thuốc Actadol là sản phẩm của Công ty Cổ phần...
2,https://nhathuoclongchau.com.vn/thuoc/allerpha...,Thuốc Allerphast 180mg Mebiphar điều trị viêm ...,2.5,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,[Fexofenadin Hydroclorid 180mg],[Allerphast được chỉ định sử dụng trong trường...,[Allerphast chống chỉ định trong các trường hợ...,"[Viêm mũi dị ứng, Người lớn và trẻ em trên 12 ...",[Chống chỉ địnhAllerphast chống chỉ định trong...,[Khi sử dụng Allerphast 180 mg thường gặp các ...,"[Tránh ánh sáng và ẩm, nhiệt độ dưới 30oC., Th...",[Allerphast 180 mg là một sản phẩm của công ty...
3,https://nhathuoclongchau.com.vn/thuoc/ambroxol...,"Siro Ambroxol Danapha điều trị viêm phế quản, ...",30.0,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,[Ambroxol hydroclorid 0.3% (kl/tt)],[Thuốc Sirô Ambroxol được chỉ định dùng trong ...,[Thuốc Ambroxol Danapha chống chỉ định trong c...,"[Trẻ em 2 - 5 tuổi2,5ml x 3 lần/ngày., Trẻ em ...",[Trước khi sử dụng thuốc bạn cần đọc kỹ hướng ...,[Khi sử dụng thuốc Sirô Ambroxol bạn có thể gặ...,"[Bảo quản nơi khô mát, tránh ánh sáng, nhiệt đ...",[Thuốc siro Ambroxol là sản phẩm của Dược Dana...
4,https://nhathuoclongchau.com.vn/thuoc/agiclovi...,Thuốc mỡ bôi da Agiclovir 5% Agimexpharm điều ...,10.0,[https//cdn.nhathuoclongchau.com.vn/unsafe/768...,"[Aciclovir 0.25g, Excipients q.s 5g]",[Thuốc mỡ bôi da Agiclovir 5%được chỉ định dùn...,[Thuốc mỡ bôi da Agiclovir 5% chống chỉ định t...,"[Thoa thuốc lên vùng da bị nhiễm, 5 - 6 lần/mỗ...",[Trước khi sử dụng thuốc bạn cần đọc kỹ hướng ...,"[Khi sử dụng thuốc mỡ bôi da Agiclovir 5%, bạn...","[Để ở nhiệt độ dưới 30C, tránh ẩm và ánh sáng....",[Thuốc mỡ bôi da Agiclovir 5% là sản phẩm của ...

In [4]:
# Data An Khang
AnKhang_df = pd.read_csv(r'D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_AnKhang\ankhang_medicines_data_full.csv')
print("Số dòng và số cột của DataFrame: ", AnKhang_df.shape)
print("Các cột trong DataFram An Khang: ", AnKhang_df.columns)
AnKhang_df.head()

Số dòng và số cột của DataFrame:  (2193, 20)
Các cột trong DataFram An Khang:  Index(['ten_thuoc', 'gia', 'hinh_anh', 'cong_dung_tom_tat', 'thanh_phan_chinh',
       'doi_tuong', 'thuong_hieu', 'noi_san_xuat', 'dang_bao_che', 'han_dung',
       'thanh_phan_chi_tiet', 'cong_dung_chi_tiet', 'cach_dung',
       'chong_chi_dinh', 'tac_dung_phu', 'luu_y', 'url', 'category',
       'drug_type', 'error'],
      dtype='object')

,ten_thuoc,gia,hinh_anh,cong_dung_tom_tat,thanh_phan_chinh,doi_tuong,thuong_hieu,noi_san_xuat,dang_bao_che,han_dung,thanh_phan_chi_tiet,cong_dung_chi_tiet,cach_dung,chong_chi_dinh,tac_dung_phu,luu_y,url,category,drug_type,error
0,"Timi Roitin trị viêm dây thần kinh, thoái hóa ...",528.000₫,https://cdn.tgdd.vn/Products/Images/10053/1304...,"Bổ sung vitamin nhóm B, điều trị viêm dây thần...","Chondroitin, Vitamin B5, Fursultiamine, Vitami...",Người lớn,Phil Inter Pharma,Việt Nam,Viên nang mềm,36 tháng kể từ ngày sản xuất,"Hoạt chất: Chondroitin sulfate natri 90mg, Nic...",- Bổ sung các vitamin nhóm B trong các trường ...,Người lớn: Uống 1 viên/ngày.\n- Quá liều\nDùng...,- Quá mẫn với bất cứ thành phần nào của thuốc....,TIMIROITIN thường được dung nạp tốt khi dùng ở...,- Thận trọng khi sử dụng\n- Khi sử dụng nicoti...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
1,B Complex C bổ sung vitamin nhóm B và vitamin ...,800₫,https://cdn.tgdd.vn/Products/Images/10053/1295...,Dự phòng & bổ sung khi thiếu hụt các vitamin n...,"Vitamin PP, Vitamin C, Vitamin B6, Vitamin B2,...",NaN,Vidipha,Việt Nam,Viên nang cứng,24 tháng kể từ ngày sản xuất,"Hoạt chất: Vitamin B1 15mg, Vitamin B2 10mg, V...",B Complex C dự phòng và bổ sung thiếu hụt các ...,Liều lượng: Trung bình: 1 - 2 viên/ngày.\nCách...,Dị ứng với một trong các thành phần của thuốc....,Dùng liều cao nước tiểu sẽ có màu vàng nhạt (d...,- Thận trọng khi sử dụng\nKhi sử dụng nicotina...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,NaN,NaN,Message: no such element: Unable to locate ele...
3,Vitamin PP 50 Pharmedic ngăn ngừa thiếu nicoti...,12.000₫,https://cdn.tgdd.vn/Products/Images/10053/1533...,Bổ sung vào khẩu phần ăn để ngăn ngừa thiếu hụ...,Vitamin PP,Người lớn và trẻ em trên 5 tuổi,Pharmedic,Việt Nam,Viên nén,NaN,Nicotinamid 50mg.\nTá dược 1 viên.,Vitamin PP 50 giúp bổ sung vào khẩu phần ăn để...,"Người lớn: mỗi lần 1 - 2 viên, ngày 3 lần.\nTr...","- Dị ứng với nicotinamid.\n- Bệnh gan nặng, lo...",NaN,- Thận trọng khi sử dụng\nNgười có tiền sử loé...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
4,"Agi-Calci bổ sung canxi, trị loãng xương (20 v...",150.000₫,https://cdn.tgdd.vn/Products/Images/10053/2463...,Bổ sung calci khi thiếu hay tăng nhu cầu calci...,"Calci cacbonat, Vitamin D3",NaN,Agimexpharm,Việt Nam,Viên nén bao phim,24 tháng kể từ ngày sản xuất,Mỗi viên nén bao phim chứa:\nHoạt chất: Calci ...,- Agi-Calci bổ sung calci trong các trường hợp...,Uống thuốc buổi sáng hoặc buổi trưa theo liều ...,"- Tăng calci huyết, calci niệu, sỏi calci, suy...",- Dùng thuốc chứa muối calci qua đường uống có...,- Thận trọng khi sử dụng\nThận trọng khi sử dụ...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN

In [5]:
# Data Pharmacity
pharmacity_df_9 = pd.read_csv(r'D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_Pharmacity\pharmacity_medicines_data_demo(9).csv')
print("Số dòng và số cột của DataFrame: ", pharmacity_df_9.shape)
print("Các cột trong DataFrame Pharmaciy: ", pharmacity_df_9.columns)
pharmacity_df_9.head()

Số dòng và số cột của DataFrame:  (3568, 24)
Các cột trong DataFrame Pharmaciy:  Index(['name', 'price', 'images', 'nha_san_xuat', 'noi_san_xuat',
       'thuoc_can_ke_don', 'hoat_chat', 'chi_dinh_tom_tat', 'dang_bao_che',
       'quy_cach', 'luu_y', 'mo_ta', 'thanh_phan', 'chi_dinh_chi_tiet',
       'huong_dan_su_dung', 'cach_su_dung', 'than_trong', 'thong_tin_san_xuat',
       'url', 'category', 'drug_type', 'category_link', 'category_name',
       'error'],
      dtype='object')

,name,price,images,nha_san_xuat,noi_san_xuat,thuoc_can_ke_don,hoat_chat,chi_dinh_tom_tat,dang_bao_che,quy_cach,...,huong_dan_su_dung,cach_su_dung,than_trong,thong_tin_san_xuat,url,category,drug_type,category_link,category_name,error
0,Viên nén Postinor 1 (Hộp 1 viên) - Ngừa thai k...,40.000 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,Gedeon Richter,Hungary,Không,LEVONORGESTREL,Thuốc tránh thai khẩn cấp trong vòng 72 giờ,Viên nén,1 vỉ X 1 viên,...,"Tác dụng phụ\n\nKhi sử dụng thuốc Postinor 1, ...",NaN,Thông tin sản xuất\nBảo quản: Bảo quản nơi khô...,NaN,https://www.pharmacity.vn/vien-nen-postinor-1-...,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN
1,Cerciorat Leon Farma (Hộp 1 vỉ x 1 viên) – Trá...,35.990 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,EXELTIS PHARMA,Spain,Không,LEVONORGESTREL,Thuốc tránh thai khẩn cấp trong vòng 72 giờ,Viên nén,1 vỉ X 1 viên,...,Thận trọng khi dùng thuốc\nChống chỉ định (Khi...,NaN,Thông tin sản xuất\nBảo quản: Ở nhiệt độ dưới ...,NaN,https://www.pharmacity.vn/cerciorat-hop-1-vi-x...,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN
2,Viên nén BOCINOR 1.5MG thuốc tránh thai khẩn c...,9.500 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,Ba Đình,NaN,NaN,LEVONORGESTREL,Thuốc tránh thai khẩn cấp trong vòng 72 giờ,Viên nén,1 vỉ X 1 viên,...,Tác dụng phụ\nQuá liều và cách xử trí\n\nCác t...,NaN,"Thông tin sản xuất\nBảo quản: Nơi khô ráo, trá...",NaN,https://www.pharmacity.vn/bocinor-tab-15mg-hop...,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN
3,Avalo day (Hộp 28 viên),25.000 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,CT CP hóa dược VN,NaN,Không,Levonorgestrel,Thuốc tránh thai,Viên nén,Hộp 1 Vỉ x 28 Viên,...,Tác dụng phụ\nChống chỉ địnhMang thai hoặc ngh...,NaN,NaN,NaN,https://www.pharmacity.vn/avalo-day-hop-28-vie...,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN
4,Newlevo 0.03mg (1 vỉ x 28 viên),8.000 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,Ba Dinh Pharma,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,https://www.pharmacity.vn/newlevo.html,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN

In [6]:
# Kết hợp tất cả DataFrame lại với nhau
combined_df = pd.concat([DieuTri_df, LongChau_df, AnKhang_df, pharmacity_df_9], ignore_index=True)
print("Số dòng và số cột của DataFrame kết hợp: ", combined_df.shape)
combined_df.head()

Số dòng và số cột của DataFrame kết hợp:  (12441, 52)

,Tên thuốc,link,Chỉ định,Thành phần,Liều dùng,Cách dùng,Tác dụng phụ,Chống chỉ định,Thận trọng,Cảnh báo,...,hoat_chat,chi_dinh_tom_tat,quy_cach,chi_dinh_chi_tiet,huong_dan_su_dung,cach_su_dung,than_trong,thong_tin_san_xuat,category_link,category_name
0,Azelastine: thuốc điều trị viêm mũi,https://www.dieutri.vn/a/azelastine-thuoc-dieu...,NaN,NaN,"Thuốc xịt mũi 0,1% (137mcg / lần xịt). 0,15% (...",NaN,Các tác dụng phụ thường gặp Vị đắng trong miện...,Quá mẫn đã được ghi nhận.,Có thể gây suy nhược thần kinh trung ương / bu...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Axit acetohydroxamic: thuốc điều trị nhiễm trù...,https://www.dieutri.vn/a/axit-acetohydroxamic-...,NaN,NaN,NaN,NaN,Tác dụng phụ thường gặp Đau đầu nhẹ; 48 giờ đầ...,Quá mẫn cảm. Bệnh nhân thích nghi với phẫu thu...,Luôn sử dụng cùng với điều trị kháng sinh thíc...,Thuốc này chứa axit acetohydroxamic. Không dùn...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Axalimogene Filolisbac: thuốc điều trị ung thư...,https://www.dieutri.vn/a/axalimogene-filolisba...,NaN,NaN,Axalimogene filolisbac đang trong quá trình th...,NaN,Mệt mỏi. Ớn lạnh. Sốt. Buồn nôn. Đau đầu. Hạ h...,Không có thông tin.,Không có thông tin.,Thuốc này chứa axalimogene filolisbac. Không d...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Avelumab: thuốc điều trị ung thư,https://www.dieutri.vn/a/avelumab-thuoc-dieu-t...,NaN,NaN,Thuốc tiêm: 20mg / ml (lọ đơn liều 200mg / 10m...,NaN,Viêm tụy. Viêm cơ tim. Viêm cơ. Suy tim sung h...,Không có.,Độc tính trên phôi thai có thể xảy ra dựa trên...,Thuốc này có chứa avelumab. Không dùng Bavenci...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Atovaquone Proguanil: thuốc điều trị sốt rét,https://www.dieutri.vn/a/atovaquone-proguanil-...,NaN,NaN,NaN,NaN,"Không có. Đau dạ dày, Ăn mất ngon, Mệt mỏi, Ng...",Quá mẫn cảm. Dự phòng ở người suy thận nặng (C...,Sử dụng thuốc này không là một phương pháp chữ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN